global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: "loadbalancer"
      static_configs:
          - targets: ["loadbalancer:8000"]
      authorization:
          type: "Bearer"
          credentials: "key" # Replace "key" with your actual API key

    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]
