{
 "title": "Loadbalancer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "description": "Number of requests per second, for the last 5 minutes",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(total_requests[5m])", "legendFormat": "Requests/sec" }
   ]
  },
  {
   "title": "Total Rate Limit Hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(total_rate_limit_hits_total[5m])",
     "legendFormat": "Hits/sec"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total number of requests",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
   "targets": [
    { "expr": "total_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "description": "Number of requests per second (last 5 mins)",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 5 },
   "targets": [
    { "expr": "rate(total_requests[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per Node per second",
   "type": "timeseries",
   "description": "Requests/s per node",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 15 },
   "targets": [
    { "expr": "rate(per_node_requests[5m])", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "per_node_requests", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Request Latency per Node",
   "type": "timeseries",
   "description": "Request latency per node",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(request_latency_seconds_sum[5m]) / rate(request_latency_seconds_count[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "barchart",
   "description": "Average latency (including all nodes). of a request",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "avg(rate(request_latency_seconds_sum[5m])) / avg(rate(request_latency_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Limit Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    { "expr": "rate(rate_limit_hits[5m])", "legendFormat": "{{node}}" }
   ]
  }
 ]
}